#code
import turtle
t = turtle.Turtle()
t.write("I'M A MATH JEDI")
t.right(90)
t.forward(2)
t.left(90)
t.forward(100)
t.penup()
t.right(90)
t.forward(10)
t.right(90)
t.shape("turtle")
t.forward(80)
t.color("blue")
#simple
import turtle
timon = turtle.Turtle()
timon.shape("turtle")
timon.color("purple")
timon.right(180)
timon.penup()
timon.forward(50)
timon.pendown()
timon.forward(50)
timon.penup()
timon.forward(30)
timon.left(180)
